services:
  Unleash\Client\Unleash: '@unleash.client.unleash'

  Unleash\Client\Configuration\UnleashConfiguration: '@unleash.client.configuration'

  Unleash\Client\Stickiness\StickinessCalculator: '@unleash.client.stickiness.murmur'
  Unleash\Client\Stickiness\MurmurHashCalculator: '@unleash.client.stickiness.murmur'

  Unleash\Client\Strategy\ApplicationHostnameStrategyHandler: '@unleash.client.strategy_handler.application_hostname'
  Unleash\Client\Strategy\DefaultStrategyHandler: '@unleash.client.strategy_handler.default'
  Unleash\Client\Strategy\GradualRolloutRandomStrategyHandler: '@unleash.client.strategy_handler.gradual_random'
  Unleash\Client\Strategy\GradualRolloutSessionIdStrategyHandler: '@unleash.client.strategy_handler.gradual_session_id'
  Unleash\Client\Strategy\GradualRolloutStrategyHandler: '@unleash.client.strategy_handler.flexible_rollout'
  Unleash\Client\Strategy\GradualRolloutUserIdStrategyHandler: '@unleash.client.strategy_handler.gradual_user_id'
  Unleash\Client\Strategy\IpAddressStrategyHandler: '@unleash.client.strategy_handler.ip_address'
  Unleash\Client\Strategy\UserIdStrategyHandler: '@unleash.client.strategy_handler.user_id'

  Unleash\Client\Configuration\Context: '@unleash.client.context'
