services:
  unleash.client.twig_extension:
    class: Unleash\Client\Bundle\Twig\UnleashTwigExtension
    arguments:
      - '@unleash.client.unleash'
      - '%unleash.client.internal.twig_functions_enabled%'
      - '%unleash.client.internal.twig_filters_enabled%'
      - '%unleash.client.internal.twig_tests_enabled%'
      - '%unleash.client.internal.twig_tags_enabled%'
    tags:
      - twig.extension
