name: Tests (8.2)
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  code_style:
    name: Test code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install
      - name: Test code style
        run: composer fixer -- --dry-run
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: composer install
      - name: Run static analysis
        run: composer phpstan
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: composer install
      - name: Run tests
        run: ./vendor/symfony/phpunit-bridge/bin/simple-phpunit
  testsTranspiled:
    name: Tests (transpiled versions)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.3', '7.4', '8.0', '8.1']
    steps:
      - name: Setup Build PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies (Build)
        run: composer install
      - name: Transpile ${{ matrix.version }}
        run: php vendor/bin/rector process --no-diffs --no-progress-bar --config rector.$(echo ${{ matrix.version }} | sed -e 's/\.//').php src
      - name: Update composer.json version
        run: 'sed -i -e ''s/"php": "\^8.2"/"php": "\^${{ matrix.version }}"/'' composer.json'
      - name: Setup Runtime PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
      - name: Install Dependencies (Runtime)
        run: composer update
      - name: Run tests
        run: ./vendor/symfony/phpunit-bridge/bin/simple-phpunit
